package statsstore

const COLUMN_ID = "id"
const COLUMN_COUNTRY = "country"
const COLUMN_CREATED_AT = "created_at"
const COLUMN_DELETED_AT = "deleted_at"
const COLUMN_IP_ADDRESS = "ip_address"
const COLUMN_PATH = "path"
const COLUMN_UPDATED_AT = "updated_at"
const COLUMN_FINGERPRINT = "fingerprint"
const COLUMN_USER_AGENT = "user_agent"
const COLUMN_USER_ACCEPT_LANGUAGE = "user_accept_language"
const COLUMN_USER_ACCEPT_ENCODING = "user_accept_encoding"
const COLUMN_USER_BROWSER = "user_browser"
const COLUMN_USER_BROWSER_VERSION = "user_browser_version"
const COLUMN_USER_DEVICE = "user_device"
const COLUMN_USER_DEVICE_TYPE = "user_device_type"
const COLUMN_USER_OS = "user_os"
const COLUMN_USER_OS_VERSION = "user_os_version"
const COLUMN_USER_REFERRER = "user_referrer"
