package ipdetails

const (
	actionLoadPaths     = "load-paths"
	actionFlagBot       = "flag-bot"
	actionFlagThreat    = "flag-threat"
	actionRemoveEntries = "remove-entries"

	FieldIP            = "ip"
	FieldCountry       = "country"
	FieldCountryName   = "country_name"
	FieldBrowser       = "browser"
	FieldBrowserVer    = "browser_version"
	FieldOS            = "os"
	FieldOSVer         = "os_version"
	FieldDevice        = "device"
	FieldDeviceType    = "device_type"
	FieldUserAgent     = "user_agent"
	FieldAcceptLang    = "accept_language"
	FieldAcceptEnc     = "accept_encoding"
	FieldReferrer      = "referrer"
	FieldFingerprint   = "fingerprint"
	FieldVisitCount    = "visit_count"
	FieldFirstSeen     = "first_seen"
	FieldLastSeen      = "last_seen"
	FieldIsBot         = "is_bot"
	FieldIsThreat      = "is_threat"
	FieldPaths         = "paths"
	FieldPath          = "path"
	FieldPathCreatedAt = "created_at"
	FieldPathMethod    = "method"
	FieldTotal         = "total"
	FieldPage          = "page"
	FieldPerPage       = "per_page"
	FieldTotalPages    = "total_pages"
	FieldDetails       = "details"
	FieldDeletedCount  = "deleted_count"
)
